### ISSUE TITLE
No device created after connection

### ISSUE THREAD

**Issue by jgagnon5541** [Ekman/home-assistant-hiveos#2]
It seems to be installing properly.  I can see in hiveos that the connection is made through the API but no device is created.   All I get is a blank box labeled HiveOS in integration.  Is there a constant I need to change in the script to make it match my rig?
![Screenshot 2022-11-04 094914](https://user-images.githubusercontent.com/14060753/199988574-265284a4-8a1e-42e7-930f-9ec7d0aa728d.png)

**Comment by Ekman** [comment]
Hey,

Thanks for reporting this issue.

For some reason, the config flow is not working as intended some times. Until that is fixed, you can set it up like so:

```yaml
switch:
  - platform: hiveos
    access_token: !secret hiveos_access_token
```
